version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"

  config-service:
    image: niluferb/config-service:1.1-SNAPSHOT
    ports:
      - "8088:8088"

  discovery-service:
    image: niluferb/discovery-service:1.1-SNAPSHOT
    ports:
      - "8061:8061"
    links:
      - config-service
    environment:
      SPRING_PROFILES_ACTIVE: docker

  employee-service:
    image: niluferb/employee-service:1.2-SNAPSHOT
    ports:
      - "8080"
    links:
      - config-service
      - discovery-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker

  department-service:
    image: niluferb/department-service:1.2-SNAPSHOT
    ports:
      - "8080"
    links:
      - config-service
      - discovery-service
      - employee-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SLEUTH_ENABLED: false  # Disable Spring Sleuth (tracing)

  organization-service:
    image: niluferb/organization-service:1.2-SNAPSHOT
    ports:
      - "8080"
    links:
      - config-service
      - discovery-service
      - employee-service
      - department-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker

  gateway-service:
    image: niluferb/gateway-service:1.1-SNAPSHOT
    ports:
      - "8060:8060"
    links:
      - config-service
      - discovery-service
      - employee-service
      - department-service
      - organization-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
